services:
    _defaults:
        autowire: true      
        autoconfigure: true

    Xver\PhpAuthCoreBundle\:
        resource: '../../../'
        exclude:
            - '../../../SymfonyFramework/'
            - '../../../Kernel.php'
            - '../../../PhpAuthCoreBundle.php'
