name: Application Quality Assurance

on:
  workflow_call:

env:
  XDEBUG_MODE: coverage

permissions:
  contents: read

jobs:
  build:
    name: Install, Build, Test and Analyze

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v7
    
    - name: Setup devbox
      uses: jetify-com/devbox-install-action@v0.15.0
      with:
        # Caching the entire Nix store in github based on your devbox.json
        enable-cache: true

    - name: Validate composer.json and composer.lock
      run: devbox run composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v6
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: devbox run composer install --prefer-dist --no-progress --optimize-autoloader

    - name: Run all test suites
      run: devbox run vendor/bin/phpunit --testsuite=all --coverage-text
       
    - name: Psalm static code analysis
      run: devbox run vendor/bin/psalm
